default:
        config:
                config: 'config/config.yaml'
                credentials_drive: 'config/credentials_drive.json'
                token_drive: 'config/token.pickle'
        data:
                entities_to_retrieve: 'data/entities/entities_to_retrieve.txt'
                entities_automatic: 'data/entities/entities_automatic.txt'
                entities_automatic_pickle: 'data/entities/entities_automatic.pkl'
                original_hashtags: 'data/entities/original_hashtags.csv'
                original_users: 'data/entities/original_users.csv'
                original_users_ids: 'data/entities/original_users_ids.csv'
                users_raw: 'data/raw/users.pkl'
                hashtags_raw: 'data/raw/hashtags.pkl'
                tweets_raw: 'data/raw/tweets.pkl'
                mentions_raw: 'data/raw/mentions.pkl'
                log: 'data/raw/log.txt'
                folder_raw: 'data/raw/'

